# Generated by Django 5.2.7 on 2025-10-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='image_url',
        ),
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reports/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='reportupdate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='updates/%Y/%m/%d/'),
        ),
    ]
