# Generated by Django 5.2.7 on 2025-10-12 09:11

import api.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_report_image_url_report_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='report',
            name='upload_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(blank=True, choices=[('Safety Hazard', 'Safety Hazard'), ('Maintenance', 'Maintenance'), ('Power Theft', 'Power Theft'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.get_report_image_path),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Pending Analysis', 'Pending Analysis'), ('Received', 'Received'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Received', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportupdate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.get_update_image_path),
        ),
    ]
