# Generated by Django 5.2.7 on 2025-10-12 09:19

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_employee_id_report_upload_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=api.models.get_report_image_path),
        ),
        migrations.AlterField(
            model_name='reportupdate',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=api.models.get_update_image_path),
        ),
    ]
