# Generated by Django 5.2.7 on 2025-10-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_report_image_alter_reportupdate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reportupdate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('In Review', 'In Review'), ('Implemented', 'Implemented'), ('Archived', 'Archived')], default='Submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
