# Generated by Django 5.2.7 on 2025-10-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_report_address_report_resolved_at_report_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ai_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
