import jinja2
from xhtml2pdf import pisa

def create_pdf_report():
    """
    Generates a PDF report from static data using an HTML template.
    """
    # --- 1. STATIC DATA (This will come from your database in the real app) ---
    report_data = {
        "report_id": "URJA-2025-001",
        "date_generated": "October 12, 2025",
        "status": "Resolved",
        "citizen": {
            "name": "Priya Singh",
            "email": "citizen.test@example.com",
            "phone": "9123456780"
        },
        "issue": {
            "submitted_at": "October 10, 2025",
            "category": "Safety Hazard",
            "description": "Broken wire is hanging dangerously from the electric pole at the main market square. It was sparking earlier this morning during the rain.",
            "image_url": "image.png", # Placeholder image URL
            "location": {
                "latitude": 23.0225,
                "longitude": 72.5714
            }
        },
        "admin": {
            "name": "Admin Kumar",
            "action_time": "October 10, 2025",
            "assigned_technician_name": "Suresh Kumar"
        },
        "technician_updates": [
            {
                "timestamp": "October 10, 2025 - 04:30 PM",
                "remark": "Reached the site. The issue is confirmed. Cordoning off the area for safety.",
                "image_url": None
            },
            {
                "timestamp": "October 11, 2025 - 11:00 AM",
                "remark": "Replacement wire has been installed and secured. The hazard is cleared. Power restored.",
                "image_url": "image.png" # Placeholder image URL
            }
        ]
    }

    # --- 2. THE HTML & CSS TEMPLATE ---
    html_template = """
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Report {{ report.report_id }}</title>
        <style>
            @page { size: A4; margin: 1.5cm; }
            body { font-family: sans-serif; color: #333; font-size: 12px; }
            .header { text-align: center; border-bottom: 2px solid #007bff; padding-bottom: 10px; margin-bottom: 25px; }
            .header h1 { color: #007bff; margin: 0; font-size: 24px;}
            .header p { margin: 5px 0; color: #666; }
            .summary-table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            .summary-table th, .summary-table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            .summary-table th { background-color: #f2f2f2; width: 30%; }
            .section { margin-top: 30px; }
            .section h2 { border-bottom: 1px solid #ccc; padding-bottom: 5px; color: #0056b3; font-size: 18px; }
            .issue-image { max-width: 90%; height: auto; margin-top: 10px; border: 1px solid #ddd; padding: 5px; display: block; margin-left: auto; margin-right: auto;}
            .update-log { margin-top: 15px; }
            .update-entry { border-left: 3px solid #007bff; padding-left: 15px; margin-bottom: 20px; page-break-inside: avoid; }
            .update-entry p { margin: 5px 0; }
            .update-entry .timestamp { font-weight: bold; color: #555; }
            .footer { position: fixed; bottom: -1cm; left: 0; right: 0; text-align: center; color: #999; font-size: 0.8em; }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>Urja Setu - Official Issue Report</h1>
            <p>Gujarat Urja Vikas Nigam Ltd. (GUVNL)</p>
        </div>

        <div class="footer">
            Generated by Urja Setu on {{ report.date_generated }}
        </div>

        <table class="summary-table">
            <tr><th>Report ID</th><td>{{ report.report_id }}</td></tr>
            <tr><th>Status</th><td>{{ report.status }}</td></tr>
            <tr><th>Submitted By</th><td>{{ report.citizen.name }} ({{ report.citizen.email }})</td></tr>
            <tr><th>Submitted On</th><td>{{ report.issue.submitted_at }}</td></tr>
            <tr><th>Assigned Technician</th><td>{{ report.admin.assigned_technician_name }}</td></tr>
        </table>

        <div class="section">
            <h2>Issue Details</h2>
            <p><strong>Category:</strong> {{ report.issue.category }}</p>
            <p><strong>Description:</strong> {{ report.issue.description }}</p>
            {% if report.issue.image_url %}
                <p><strong>Visual Evidence Submitted by Citizen:</strong></p>
                <img src="{{ report.issue.image_url }}" alt="Citizen submitted image" class="issue-image">
            {% endif %}
        </div>

        <div class="section">
            <h2>Technician Action Log</h2>
            <div class="update-log">
                {% for update in report.technician_updates %}
                    <div class="update-entry">
                        <p class="timestamp">{{ update.timestamp }}</p>
                        <p><strong>Remark:</strong> "{{ update.remark }}"</p>
                        {% if update.image_url %}
                            <p><strong>Attached Image:</strong></p>
                            <img src="{{ update.image_url }}" alt="Technician update image" class="issue-image">
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
        </div>
    </body>
    </html>
    """

    # --- 3. RENDER THE TEMPLATE AND GENERATE PDF ---
    template = jinja2.Template(html_template)
    rendered_html = template.render(report=report_data)

    output_filename = "report_output.pdf"
    
    # Use xhtml2pdf to convert HTML to PDF
    with open(output_filename, "w+b") as pdf_file:
        pisa_status = pisa.CreatePDF(
            rendered_html,      # The HTML string to convert
            dest=pdf_file)      # The file handle to write to

    if pisa_status.err:
        print(f"Error converting HTML to PDF: {pisa_status.err}")
    else:
        print(f"✅ Success! '{output_filename}' has been generated.")

if __name__ == '__main__':
    create_pdf_report()